"""empty message

Revision ID: 982058614e9b
Revises: 
Create Date: 2018-01-23 04:49:30.297900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982058614e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
